### ISSUE TITLE
How to get process.env.RAILS_ENV?

### ISSUE THREAD

**Issue by geoRG77** [vigetlabs/gulp-rails-pipeline#14]
Hi, 
thanks for your repo, very nice work!

I only have problem with `process.env.RAILS_ENV`, as it's always undefined. I guess you must be using some Rails code to set this, maybe `.env` file?

Thanks

**Comment by geoRG77** [comment]
I guess I found it out: `export RAILS_ENV=production`, right?

**Comment by greypants** [comment]
Yep, that's a way. I think I've only been explicitly using it on Heroku, and I set up the environment variables through the admin. You can also set it on the command line before whatever command you run `RAILS_ENV=production gulp`
