### ISSUE TITLE
Some questions and feature requests

### ISSUE THREAD

**Issue by nowhereman** [vigetlabs/gulp-rails-pipeline#3]
Hi @greypants,

Your gem looks pretty cool,  but I have some questions.
- Does it supports *.js.erb files or at least *.js.ejs files? 
- Do you plan to support source mapping?

Cheers,
Nowhere Man

**Comment by greypants** [comment]
Hola. To clarify, this isn't a gem - it's just an example of how to go about setting up a Gulp based asset pipeline. At the moment, you'd have to copy everything over to your own project manually. 

Source maps are already set up and working with both sass and js/coffee. Let me know if that's not the case.

The `.js.erb` stuff was Rails Asset Pipeline specific. You could still use the Rails Asset Pipeline if you need Ruby to transform your files first. Just put those files in `app/assets` and `//require=` them like you always have. Alternatively, if there's some data your JS needs from your app, you could always throw it inline in your view on a data-attribute, or in a script tag.

As far as ejs goes, you can use whatever JavaScript templating language you want. There are browserify transforms for all of them. Here's one for ejs: https://github.com/hughsk/ejsify

These transforms let you require templates as if they were js files. See https://github.com/greypants/gulp-starter/blob/master/src/javascript/view.coffee#L8 and https://github.com/greypants/gulp-starter/blob/master/src/javascript/template.hbs for an example using handlebars and hbsify.

Hope that helps!
