### ISSUE TITLE
Fails to build on heroku

### ISSUE THREAD

**Issue by mtc2013** [vigetlabs/gulp-rails-pipeline#36]
Error: Cannot find module 'gulp-watch'
remote:        at Function.Module._resolveFilename (module.js:338:15)
remote:        at Function.Module._load (module.js:280:25)
remote:        at Module.require (module.js:364:17)
remote:        at require (module.js:380:17)
remote:        at Object.<anonymous> (/tmp/build_310d1461a5bfcb66a7cd499838db21ac/gulp/tasks/watch.js:8:14)
remote:        at Module._compile (module.js:456:26)
remote:        at Object.Module._extensions..js (module.js:474:10)
remote:        at Module.load (module.js:356:32)
remote:        at Function.Module._load (module.js:312:12)
remote:        at Module.require (module.js:364:17)

It appears gulp-watch is required on in tasks/watch.js which is apparently being somehow run when heroku runs gulp build.  I'm not sure how exactly as I am a gulp/nodejs newbie.  But of course, gulp-watch is only a dev dependency and so not on heroku.

**Comment by mikesmayer** [comment]
I'm running into the same issue -- have you had any success solving this?

**Comment by greypants** [comment]
hm. I'll look into this... weird that this is just now popping up. We haven't changed anything here in quite some time.

**Comment by chintanparikh** [comment]
Hey all - just fixed this with `npm install --save gulp-watch` (and thus making it an actual dependency).

**Comment by greypants** [comment]
thanks @chintanparikh. Fixed.
