### ISSUE TITLE
Grunt version

### ISSUE THREAD

**Issue by rctneil** [vigetlabs/gulp-rails-pipeline#4]
Hey

Is there a Grunt version of this as it would be exactly what I'm looking for.

**Comment by greypants** [comment]
I've come across some blog posts where people tried this with Grunt - but I don't know that the solutions addressed all the issues I've tried to do here. I'm sure you could apply the same concepts and accomplish something similar. The big thing to remember is to have a way to still integrate with the existing pipeline when needed.

Have you tried Gulp? I learned both Grunt and Gulp within a week of each other, and was really really impressed with Gulp. Been using it for over a year now, and I'm still loving it. There are plugins for pretty much everything now, and development is super active. I have no plans to go back.

**Comment by rctneil** [comment]
Just started looking at Gulp. It is similar to Grunt but the syntax seems different. Will give it a try and run through your project. Thanks!

**Comment by greypants** [comment]
No problem! If you want to play with gulp without worrying about the rails parts, check out https://github.com/greypants/gulp-starter (there's also a 2.0 branch on there that's still in flux, but a little cleaner and more robust)
