### ISSUE TITLE
Use gulp_asset_path in scss

### ISSUE THREAD

**Issue by Luxbit** [vigetlabs/gulp-rails-pipeline#45]
I'm wondering how to link images or fonts in scss.

Is there an easy way to get the `gulp_asset_path` working in scss ?

**Comment by greypants** [comment]
the `rev` step does a string replace of matched paths based on the generated `rev-manifest.json` file.  So something like `assets/images/cat.gif` would get replaced with `assets/images/cat-aw802hfa2de.gif` out of the box.
