### ISSUE TITLE
Doesn't compile image-url sprockets helper

### ISSUE THREAD

**Issue by Hirurg103** [vigetlabs/gulp-rails-pipeline#48]
I cloned the project, installed gems/npm packages, compiled assets and opened http://localhost:3000/

I see the following in my browser: 
![screen shot 2016-03-09 at 1 28 41 pm](https://cloud.githubusercontent.com/assets/2171773/13632470/f1ac0d00-e5fa-11e5-839a-372e87ffd6b3.png)

When I open the compiled public/assets/stylesheets/global.css I see 

``` css
body {
  background: #dd3435 image-url("gulp.png");
  font-family: sans-serif; }
```

which is an invalid CSS rule. When I fix image-url to url manually and open the page again I see the following

![screen shot 2016-03-09 at 1 32 14 pm](https://cloud.githubusercontent.com/assets/2171773/13632575/611298e4-e5fb-11e5-9632-86c974dfc10c.png)

I could change the background rule in the [global.sass](https://github.com/vigetlabs/gulp-rails-pipeline/blob/master/gulp/assets/stylesheets/global.sass) to  

``` css
background: #dd3435 url('gulp.png')
```

but seems that it won't work in the production because of the digest in the image filename

How can we fix this issue? Do you have any ideas?

**Comment by greypants** [comment]
Oh man. Yeah, `image-url` used to be a thing in `node-sass` a long time ago. It's since been deprecated. It should be removed in favor of putting the full asset path a regular `url()` declaration.

``` css
background: #dd3435 url("assets/images/gulp.png");
```

This repo is in need of an update. In the meantime, you can reference https://github.com/vigetlabs/gulp-starter for a more up to date tasks and dependencies.

**Comment by Hirurg103** [comment]
OK, thank you very much @greypants !

**Comment by greypants** [comment]
We can leave this open, as I need to update the example code.

**Comment by chrisvanpatten** [comment]
Worth noting that you can also use the [node-sass-asset-functions](https://github.com/fetch/node-sass-asset-functions) library to maintain this functionality.

**Comment by soundasleep** [comment]
I couldn't get the background image to work unless I changed the SASS to:

```sass
background: #dd3435 url("images/gulp.png")
```
